FROM node:18

# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/app
COPY package*.json ./
RUN npm ci
ENV PATH /usr/app/node_modules/.bin:$PATH


COPY . .
RUN chown -R node:node /usr/app
USER node
RUN ["npm", "build"]
EXPOSE 1337

CMD ["npm", "run", "develop"]